version: '3.9'
services:
    app:
        image: extender777/isocraft
        ports:
            - '8011:3000'
        environment:
            - NODE_ENV=production
            - STABILITY_KEY=${STABILITY_KEY}
            - OPENAI_KEY=${OPENAI_KEY}
            - TOGETHER_KEY=${TOGETHER_KEY}
            - JWT_SECRET=${JWT_SECRET}
            - MONGODB_URI=mongodb://mongodb:27017/isocraft
        depends_on:
            - mongodb
        restart: unless-stopped
        volumes:
            - ./content:/app/content

    mongodb:
        image: mongo:latest
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped
        logging:
            driver: none

volumes:
    mongodb_data:
