version: '3.9'
services:
    app:
        image: extender777/isocraft
        ports:
            - '8011:3000'
        environment:
            - NODE_ENV=production
            - STABILITY_KEY=${STABILITY_KEY}
            - JWT_SECRET=${JWT_SECRET}
            - MONGODB_URI=mongodb://mongodb:27017/isocraft
            - REDIS_URL=redis://redis:6379
        depends_on:
            - mongodb
            - redis
        restart: unless-stopped

    mongodb:
        image: mongo:latest
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped

    redis:
        image: redis:alpine
        restart: unless-stopped

volumes:
    mongodb_data:
