name: IsoCraft CI/CD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: copy file via ssh
              uses: garygrossgarten/github-action-scp@master
              with:
                  host: isocraft.online
                  username: ubuntu
                  privateKey: ${{ secrets.DEPLOY_KEY }}
                  local: './docker-compose.yml'
                  remote: 'isocraft/docker-compose.yml'

            - name: Use Node.js
              uses: actions/setup-node@master
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Build frontend
              run: npm run build

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@master

            - name: Log in to Docker Hub
              uses: docker/login-action@master
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Backend Image (arm64)
              run: |
                  docker buildx build \
                  --platform linux/arm64/v8 \
                  --output "type=image,push=true" \
                  --tag ${{ secrets.DOCKER_USERNAME }}/isocraft \
                  .

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to SSH Host
              env:
                  SSH_KEY: ${{ secrets.DEPLOY_KEY }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H isocraft.online >> ~/.ssh/known_hosts
                  ssh ubuntu@isocraft.online '
                    docker pull ${{ secrets.DOCKER_USERNAME }}/isocraft
                    cd isocraft
                    docker-compose down
                    docker-compose up -d
                  '
